[package]
name = "day07"
version = "0.1.0"
authors = ["Nick Pfundstein <nickpfundstein@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.5.9"
chrono = "0.4.10"
log = "0.4.8"
